### ISSUE TITLE
suitability on untrusted zip files

### ISSUE THREAD

**Issue by v-gb** [dbuenzli/zipc#1]
Hello,

I'm writing a server that is meant to read epubs (and other things) from untrusted clients, thus the question of: can I reject files that would requires unreasonable amount of memory to decompress (intentionally or accidentally)?

The file size metadata is all that's needed for non-adversarial inputs.
I'm wondering if the library could make it possible to enforce that the size is no bigger than the file size metadata, so the guarantees are simpler. From a quick look at the code, it looks straightforward:

```diff
 module Buf = struct
-  type t = { mutable b : bytes; mutable len : int; }
+  type t = { mutable b : bytes; mutable len : int; max_size : int }

   let grow ~ensure buf =
     let newlen = ref (Bytes.length buf.b) in
     let () = while !newlen < ensure do newlen := 2 * !newlen done in
     let () =
-      if !newlen <= Sys.max_string_length then () else
-      if ensure <= Sys.max_string_length then newlen := ensure else
+      if !newlen <= buf.max_size then () else
+      if ensure <= buf.max_size then newlen := ensure else
+      (* if ensure <= buf.max_size then newlen := buf.max_size else *) (* this one looks better, actually. The current code may not have the right complexity *)
       failwith "OCaml string size exceeded"
     in
     let b = Bytes.create !newlen in
     Bytes.blit buf.b 0 b 0 buf.len; buf.b <- b

   ...
 end
```

And then pass the `?max_size` flag in `Zipc.File`,  presumably.

What do you think? (I can make a pull request, if you're fine with the suggestion)

**Comment by dbuenzli** [comment]
Seen under this angle ignoring the file size metadata doesn't look like a great security default. 

I think we should rather simply change [`Zipc.File.to_binary_string`](https://erratique.ch/software/zipc/doc/Zipc/File/index.html#val-to_binary_string) to error as soon as the decompressed file size metadata is exceeded. This may entail a bit of API changes at the `Zipc_deflate` level, I'll have a look into that. 

That being said if you want to sandbox the memory consumption of your untrusted input processing in a more general manner you may be interested in @gadmm's [`memprof-limits`](https://ocaml.org/p/memprof-limits/0.2.0).

**Comment by v-gb** [comment]
Ah, I didn't really have memprof-limits under my radar. It's probably limited, compared to the direct approach of rejecting large files. For instance, if you have multiple domains, I can't imagine that memprof-limits would be able to limit memory usage (not just memory allocations) caused by the specific domains that are currently decompressing. But memprof-limits might be useful as an alternative to `ulimit -v`.

**Comment by gadmm** [comment]
Thanks for mentioning memprof-limits. 2 cents:

Global memory limits work as @v-gb says.
Depending on what you know about the function, allocation limits could be a proxy for memory consumption (if it is not necessary to count deallocations).
I could add local memory limits for this purpose (counting both allocations and deallocations in a single function), but I'd have to think a bit about the probabilistic guarantees.

Most importantly, memprof-limits would require Zipc.File.to_binary_string itself to be written to be interrupt-safe and documented to be so.

**Comment by gadmm** [comment]
Thanks for mentioning memprof-limits. My 2 cents:

Global memory limits work as @v-gb says.
Depending on what you know about the function, allocation limits could be a proxy for memory consumption (i.e. whenever  is not necessary to count deallocations to extrapolate the memory consumption).
I could add local memory limits for this specific purpose (counting both allocations and deallocations in a single function), but I'd have to think a bit about the probabilistic guarantees before that.

Most importantly, Zipc.File.to_binary_string itself would need to be written to be interrupt-safe, and documented as such.

**Comment by v-gb** [comment]
Thanks !
