### ISSUE TITLE
modifying a zip with data descriptors results in invalid zip file

### ISSUE THREAD

**Issue by v-gb** [dbuenzli/zipc#4]
Currently, taking a .docx produced by libreoffice, and passing it through `Zipc.of_binary_file` and `Zipc.to_binary_file` results in a file that Word chokes on. Other tools seem happy, but I think Word is stricter but not wrong.

I'm not quite finished digging, but I know at least the following:
- the file headers in the input have gp flag bit 3 set. 
- when that happens, all of https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT, https://en.wikipedia.org/wiki/ZIP_(file_format) and https://ecma-international.org/publications-and-standards/standards/ecma-376/ table B.5 say that the file should have a data descriptor
- the files that are output by zipc keep the gp flag, but don't produce (or drop) the data descriptors. Concretely, there are 16 bytes after each file content of the initial zip that don't end up in the new file, and these 16 bytes contains things like "PK\007\b\152\173\197\n\221\000\000\000D\002\000\000", where ""PK\007\b" is the optional signature, the next four bytes are the crc32 and I'm not sure what the rest is.

Adding the 16 bytes of data descriptors from the original file makes Word accept the file.
What I'm confused about is why clearing the gp flag doesn't seem to solve the problem.

**Comment by v-gb** [comment]
Clearing the gp flag probably doesn't help because the data in the local file header is bad without it (crc, compressed size and decompressed size are 0, which Word might be checking).

**Comment by dbuenzli** [comment]
Thank you very much for tracking this down. Indeed `zipc`'s encoding is clearly wrong here. However:

> Clearing the gp flag probably doesn't help because the data in the local file header is bad without it (crc, compressed size and decompressed size are 0, which Word might be checking).

I don't think so. `zipc` is (re)writing the local file header based on the central directory data only (see first point [here](https://erratique.ch/software/zipc/doc/Zipc/index.html#val-of_binary_string)). So I rather simply make sure we clear the flag on write rather than what you propose in #7. 

Commit 147c254 does this, could you please confirm that it solves the issue.

**Comment by dbuenzli** [comment]
> * https://ecma-international.org/publications-and-standards/standards/ecma-376/ table B.5 say that the file should have a data descriptor

That looks a bit contradictory. Section B.2 mentions that data descriptors may not exist and table B.1 under "Data descriptor" has "Optional" for "Supported on production". I think (or hope) it should be fine to produce `docx` files that have no data descriptors.

**Comment by v-gb** [comment]
> I don't think so. zipc is (re)writing the local file header based on the central directory data only (see first point [here](https://erratique.ch/software/zipc/doc/Zipc/index.html#val-of_binary_string)). So I rather simply make sure we clear the flag on write rather than what you propose in https://github.com/dbuenzli/zipc/pull/7.
>
> Commit https://github.com/dbuenzli/zipc/commit/147c2547063ded6d16076e56a187fc6ffad0b4d4 does this, could you please confirm that it solves the issue.

It works, thanks.

(which I'm confused about, because that's exactly what I tried first when I mentioned clearing the flag. I even have a commit showing pretty much the same code as you. But anyway, the problem is fixed and I've spent long enough debugging the problem, I'm not going to start debugging my debugging)

**Comment by dbuenzli** [comment]
> I've spent long enough debugging the problem

Thanks again for going to the bottom of these things. I hope there's not too much other transcoding pitfalls and stupid encoding errors lurking in the code. 

If you feel that's not the case I'm happy to do a release whenever you request.

**Comment by v-gb** [comment]
I think it's reasonable to make a release.

I don't expect more problems, because:
- the first problem came from feeding a Word file into zipc into Word
- the second from feeding a LibreOffice file into zipc into Word (neither unzip nor LibreOffice seem to ever complain)
- I have no other program to make docx files ! (I actually just thought of google docs, so I fed a docx from it into zipc into Word, which worked, so that breaks the pattern thankfully)
