### ISSUE TITLE
Support for integer compression level for DEFLATE algorithm.

### ISSUE THREAD

**Issue by zoj613** [dbuenzli/zipc#9]
I see that the compression level for the DEFLATE algorithm is defined as
```ocaml
type level = [ `None | `Fast | `Default | `Best ]
```
but what if someone wants to specify the compression level using the integer levels from 0 to 9? A use case for this is say, replacing `camlzip` with `zipc` for opening and writing to a zip file because `camlzip` is LGPL licensed and may cause potential issues vs `zipc` which uses the permissive ICS license. It would be nice to keep a high level API that uses `type level = int` unchanged and be able to map an integer value to a `Zipc_deflate.level` type value. Any way I can achieve this? It's hard to tell what `Fast`, `Default` or `Best` mean when thinking of the compression level in terms of integer values.

**Comment by dbuenzli** [comment]
> I see that the compression level for the DEFLATE algorithm is defined as
[…]
> but what if someone wants to specify the compression level using the integer levels from 0 to 9?

There is no such in DEFLATE. The libz implementation added this notion of integer level for sizing some of its internal data structures. 

In practice, I don't find these integers to be very useful. People either want a good compression/speed tradeoff (`Default`), or fast compression (`Fast` or `None`) or best compression (`Best`). I don't think it's worth adding more options here. In `zipc` [here](https://github.com/dbuenzli/zipc/blob/48464a2bfe608e65282a2534f4fc3751e5fa8ed6/src/zipc_deflate.ml#L754-L764) is how these levels are translated. 

> It's hard to tell what Fast, Default or Best mean when thinking of the compression level in terms of integer values.

You can just use the integer of the corresponding zlib define ( `Z_BEST_SPEED`, `Z_BEST_COMPRESSION`, etc. see [this page](https://zlib.net/manual.html))

**Comment by zoj613** [comment]
> There is no such in DEFLATE

I had a feeling this was the case because I couldn't find a reference to the integer compression levels when reading up on it.

> In practice, I don't find these integers to be very useful. People either want a good compression/speed tradeoff (Default), or fast compression (Fast or None) or best compression (Best). I don't think it's worth adding more options here.

That is fine with me. I think i'll just add a docstring that tries to communicate what these levels mean when attempting to translate them to integers.
